# Generated by Django 2.2 on 2024-06-25 14:25

import colossus.apps.autocampaign.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0007_auto_20240212_0827'),
        ('lists', '0003_mailinglist_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_numbers', models.PositiveIntegerField(default=50, validators=[colossus.apps.autocampaign.models.validate_positive], verbose_name='mail numbers')),
                ('pdf_file', models.CharField(choices=[('Recipe-Lead-Magnet.pdf', 'Recipe-Lead-Magnet.pdf')], max_length=255, verbose_name='PDF file')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update date')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_campaigns', to='campaigns.Campaign', verbose_name='campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('mailing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_campaigns', to='lists.MailingList', verbose_name='mailing list')),
            ],
        ),
    ]
