# Generated by Django 2.2 on 2024-06-21 14:14

import colossus.apps.autocampaign.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0007_auto_20240212_0827'),
        ('lists', '0003_mailinglist_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_numbers', models.PositiveIntegerField(default=50, validators=[colossus.apps.autocampaign.models.validate_positive], verbose_name='mail numbers')),
                ('pdf_file', models.CharField(max_length=255, verbose_name='PDF file')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_campaigns', to='campaigns.Campaign', verbose_name='campaign')),
                ('mailing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_campaigns', to='lists.MailingList', verbose_name='mailing list')),
            ],
        ),
    ]
