# Generated by Django 2.2 on 2024-06-24 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autocampaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocampaign',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autocampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='autocampaign',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='update date'),
        ),
        migrations.AlterField(
            model_name='autocampaign',
            name='pdf_file',
            field=models.CharField(choices=[('Recipe-Lead-Magnet.pdf', 'Recipe-Lead-Magnet.pdf')], max_length=255, verbose_name='PDF file'),
        ),
    ]
