# Generated by Django 2.2 on 2024-06-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocampaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocampaign',
            name='send_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='send date'),
        ),
        migrations.AddField(
            model_name='autocampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='autocampaign',
            name='pdf_file',
            field=models.CharField(choices=[('PDFsRecipe-Lead-Magnet.pdf', 'PDFsRecipe-Lead-Magnet.pdf')], max_length=255, verbose_name='PDF file'),
        ),
    ]
