# Generated by Django 2.2 on 2024-07-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocampaign', '0002_auto_20240627_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocampaign',
            name='pdf_file',
            field=models.CharField(blank=True, choices=[('PDFsRecipe-Lead-Magnet.pdf', 'PDFsRecipe-Lead-Magnet.pdf')], max_length=255, null=True, verbose_name='PDF file'),
        ),
    ]
