# Generated by Django 2.2 on 2024-07-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocampaign', '0003_auto_20240703_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocampaign',
            name='pdf_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PDF file'),
        ),
    ]
