# Generated by Django 2.2 on 2023-11-11 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_auto_20181112_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mailing_lists', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
