# Generated by Django 2.2 on 2023-04-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0010_auto_20180825_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='lists.MailingList'),
        ),
    ]
