# Generated by Django 2.2 on 2024-02-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0011_auto_20230423_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_bad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='lists.MailingList'),
        ),
    ]
