# Generated by Django 2.2 on 2024-02-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0011_auto_20230423_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
            ],
        ),
    ]
