# Generated by Django 2.2 on 2024-03-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0013_unsubscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsubscribers',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
